# Generated by Django 6.0.6 on 2026-07-06 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('grupo_muscular', models.CharField(choices=[('pierna', 'Pierna'), ('gluteo', 'Glúteo'), ('espalda', 'Espalda'), ('pecho', 'Pecho'), ('brazo', 'Brazo'), ('core', 'Core / abdomen'), ('cuerpo_completo', 'Cuerpo completo')], max_length=20)),
                ('descripcion_tecnica', models.TextField(help_text='Cómo se hace correctamente, en qué fijarse, errores comunes.')),
                ('video_url', models.URLField(blank=True, help_text='Enlace a un video (YouTube, etc.) que muestre la técnica.')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('fuerza', 'Fuerza'), ('cardio', 'Cardio')], default='fuerza', max_length=10)),
                ('lugar', models.CharField(choices=[('casa', 'En casa'), ('gimnasio', 'En gimnasio')], max_length=10)),
                ('nivel', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=15)),
                ('equipo', models.CharField(choices=[('ninguno', 'Sin equipo'), ('mancuernas', 'Mancuernas'), ('bandas', 'Bandas'), ('gimnasio_completo', 'Equipo de gimnasio')], default='ninguno', max_length=20)),
                ('tipo_cardio', models.CharField(blank=True, choices=[('caminar', 'Caminar'), ('bicicleta', 'Bicicleta'), ('correr', 'Correr'), ('hiit', 'HIIT')], help_text="Solo si la categoría es 'Cardio'.", max_length=15)),
                ('minutos_duracion', models.PositiveSmallIntegerField(help_text='Duración aproximada en minutos.')),
                ('descripcion', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['lugar', 'nivel', 'minutos_duracion'],
            },
        ),
        migrations.CreateModel(
            name='RutinaEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('series', models.PositiveSmallIntegerField(default=3)),
                ('repeticiones', models.CharField(default='12', help_text="Ej. '12', '10-15', '30 segundos'.", max_length=30)),
                ('descanso_segundos', models.PositiveSmallIntegerField(default=45)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutinas.ejercicio')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutina_ejercicios', to='rutinas.rutina')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='rutina',
            name='ejercicios',
            field=models.ManyToManyField(through='rutinas.RutinaEjercicio', to='rutinas.ejercicio'),
        ),
    ]
