# Generated by Django 6.0.6 on 2026-07-06 22:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetoSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CompaneraDeCompromiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emparejamiento', models.DateField(default=django.utils.timezone.now)),
                ('activa', models.BooleanField(default=True)),
                ('usuario_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario_1', 'usuario_2')},
            },
        ),
        migrations.CreateModel(
            name='Frase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=300)),
                ('origen', models.CharField(choices=[('sistema', 'Sistema (personalizada por momento)'), ('comunidad', 'Compartida por la comunidad')], default='sistema', max_length=12)),
                ('momento', models.CharField(choices=[('dia_1', 'Arrancando (día 1-3)'), ('racha_activa', 'Racha activa (7+ días)'), ('racha_rota', 'Día después de faltar'), ('estancamiento', 'Estancamiento (2-3 semanas sin cambio)'), ('domingo', 'Domingo (planeación de la semana)'), ('general', 'General / cualquier momento')], default='general', max_length=20)),
                ('aprobado', models.BooleanField(default=True, help_text='Para frases de comunidad, empieza en False hasta moderar.')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('compartida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frases_compartidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MensajeCompanera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=300)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('pareja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='community.companeradecompromiso')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['creado'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('comida', 'Comida'), ('entrenamiento', 'Entrenamiento'), ('logro', 'Logro')], max_length=15)),
                ('texto', models.CharField(blank=True, max_length=500)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='posts/%Y/%m/')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('economica', 'Económica'), ('vegetariana', 'Vegetariana'), ('oficina', 'Para oficina'), ('mexicana', 'Mexicana'), ('rapida', 'Rápida'), ('familiar', 'Familiar'), ('meal_prep', 'Meal prep / domingo'), ('flexible', 'Flexible (80/20)'), ('snack', 'Snack / colación')], max_length=20)),
                ('ingredientes', models.TextField(help_text='Un ingrediente por línea.')),
                ('preparacion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='recetas/%Y/%m/')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('aprobado', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to=settings.AUTH_USER_MODEL)),
                ('guardada_por', models.ManyToManyField(blank=True, related_name='recetas_favoritas', to=settings.AUTH_USER_MODEL)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Reaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(choices=[('🔥', 'Sigue así'), ('💪', 'Yo también entrené hoy'), ('👏', 'Felicidades')], max_length=5)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacciones', to='community.post')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('post', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='ParticipacionReto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='community.retosemanal')),
            ],
            options={
                'unique_together': {('reto', 'usuario')},
            },
        ),
    ]
