# Generated by Django 6.0.6 on 2026-07-06 22:59

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tono_mensajes', models.CharField(choices=[('suave', 'Motivación cercana y comprensiva'), ('directo', 'Directo y sin filtros')], default='suave', help_text='Cómo prefiere la usuaria que le hablemos en frases y notificaciones.', max_length=10)),
                ('nombre_para_mostrar', models.CharField(blank=True, help_text="Nombre con el que se le saluda en el dashboard (ej. 'María').", max_length=50)),
                ('edad', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('estatura_cm', models.PositiveSmallIntegerField(blank=True, help_text='Estatura en centímetros.', null=True)),
                ('peso_inicial_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('cintura_inicial_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('objetivo', models.CharField(choices=[('bajar_peso', 'Bajar de peso'), ('tonificar', 'Tonificar'), ('ganar_musculo', 'Ganar músculo'), ('salud_general', 'Salud general / sentirme mejor')], default='salud_general', max_length=20)),
                ('lugar_entreno', models.CharField(choices=[('casa', 'En casa'), ('gimnasio', 'En gimnasio')], default='casa', max_length=10)),
                ('nivel', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='principiante', max_length=15)),
                ('minutos_disponibles', models.PositiveSmallIntegerField(default=30, help_text='Minutos disponibles por sesión (20, 30, 45, 60...).')),
                ('lesiones', models.TextField(blank=True, help_text='Lesiones o limitaciones físicas a tener en cuenta al sugerir rutinas.')),
                ('horario_preferido', models.CharField(blank=True, help_text="Ej. 'mañanas antes del trabajo', 'noches'.", max_length=100)),
                ('fecha_inicio_compromiso', models.DateField(default=django.utils.timezone.now, help_text="Día 1 de su compromiso. Se usa para mostrar 'Día X de tu compromiso'.")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
