# Generated by Django 6.0.6 on 2026-07-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='preferencia_alimenticia',
            field=models.CharField(choices=[('omnivoro', 'Como de todo'), ('vegetariana', 'Vegetariana'), ('vegana', 'Vegana'), ('sin_gluten', 'Sin gluten')], default='omnivoro', help_text='Se usa para recomendarte dietas compatibles con lo que comes.', max_length=15),
        ),
        migrations.AddField(
            model_name='usuario',
            name='presupuesto_comida',
            field=models.CharField(choices=[('economico', 'Económico'), ('moderado', 'Moderado'), ('alto', 'Sin restricción de presupuesto')], default='moderado', help_text='Cuánto puede/quiere gastar en su alimentación.', max_length=10),
        ),
    ]
