# Generated by Django 6.0.6 on 2026-07-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usuario_preferencia_alimenticia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='horario_preferido',
            field=models.CharField(choices=[('manana', 'Mañana'), ('tarde', 'Tarde'), ('noche', 'Noche'), ('variable', 'Variable / no tengo un horario fijo')], default='variable', help_text='Se usa, entre otras cosas, para emparejarte con una compañera de compromiso.', max_length=10),
        ),
    ]
