# Generated by Django 6.0.6 on 2026-07-06 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('momento_sugerido', models.CharField(choices=[('desayuno', 'Desayuno'), ('colacion_am', 'Colación (mañana)'), ('comida', 'Comida'), ('colacion_pm', 'Colación (tarde)'), ('cena', 'Cena')], max_length=15)),
                ('ingredientes', models.TextField(help_text='Un ingrediente por línea, con cantidades.')),
                ('preparacion', models.TextField(blank=True, help_text='Pasos rápidos de preparación.')),
                ('calorias_aprox', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('economica', 'Económica'), ('vegetariana', 'Vegetariana'), ('vegana', 'Vegana'), ('mexicana', 'Mexicana'), ('meal_prep', 'Meal prep / domingo'), ('alta_proteina', 'Alta en proteína'), ('baja_carbohidratos', 'Baja en carbohidratos'), ('sin_gluten', 'Sin gluten'), ('rapida', 'Rápida / poco tiempo'), ('tradicional', 'Tradicional / casera')], max_length=20)),
                ('objetivo', models.CharField(choices=[('bajar_peso', 'Bajar de peso'), ('tonificar', 'Tonificar'), ('ganar_musculo', 'Ganar músculo'), ('salud_general', 'Salud general / sentirme mejor')], default='salud_general', max_length=20)),
                ('preferencia', models.CharField(choices=[('omnivoro', 'Como de todo'), ('vegetariana', 'Vegetariana'), ('vegana', 'Vegana'), ('sin_gluten', 'Sin gluten')], default='omnivoro', max_length=15)),
                ('presupuesto', models.CharField(choices=[('economico', 'Económico'), ('moderado', 'Moderado'), ('alto', 'Sin restricción de presupuesto')], default='moderado', max_length=10)),
                ('comidas_por_dia', models.PositiveSmallIntegerField(default=4)),
                ('calorias_aproximadas', models.PositiveSmallIntegerField(blank=True, help_text='Calorías aproximadas por día.', null=True)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name_plural': 'dietas',
                'ordering': ['categoria', 'objetivo'],
            },
        ),
        migrations.CreateModel(
            name='DietaComida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('comida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dietas.comida')),
                ('dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dieta_comidas', to='dietas.dieta')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='dieta',
            name='comidas',
            field=models.ManyToManyField(through='dietas.DietaComida', to='dietas.comida'),
        ),
    ]
