# Generated by Django 6.0.6 on 2026-07-06 22:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('icono', models.CharField(default='🏅', help_text='Emoji o clase de ícono para mostrar.', max_length=10)),
                ('tipo_condicion', models.CharField(choices=[('racha_dias', 'Racha de días consecutivos'), ('total_entrenamientos', 'Total de entrenamientos acumulados'), ('kilos_perdidos', 'Kilos perdidos desde el inicio'), ('manual', 'Otorgada manualmente')], max_length=25)),
                ('valor_condicion', models.PositiveSmallIntegerField(help_text='Ej. 7 (para racha de 7 días), 100 (para 100 entrenamientos).')),
            ],
        ),
        migrations.CreateModel(
            name='FotoProgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='progreso/%Y/%m/')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('nota', models.CharField(blank=True, max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_progreso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='MedallaObtenida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtenida', models.DateField(default=django.utils.timezone.now)),
                ('medalla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.medalla')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medallas_obtenidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'medalla')},
            },
        ),
        migrations.CreateModel(
            name='RegistroDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('entreno', models.BooleanField(default=False, help_text='¿Entrenó este día?')),
                ('minutos_entrenados', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tomo_agua_meta', models.BooleanField(default=False, help_text='¿Cumplió su meta de agua del día?')),
                ('horas_sueno', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('cintura_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('momento_dificil', models.CharField(blank=True, help_text="Respuesta libre: '¿qué fue lo más difícil hoy?'", max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('usuario', 'fecha')},
            },
        ),
    ]
